myString = "Fiecare caracter are propriul sau index"
#print(len(myString))
#print(myString[0])
#print(myString[-1])
#print(myString[-3])
#print(myString[5: 8])
#print(myString[::-1])
print(myString[:-3])
slicedString = slice(2)
print(myString[slicedString])
print(myString[:2])
print(myString[0:2])
print(myString[3:-1])